// <auto-generated />
using System;
using Market.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Market.Services.CouponAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231230013716_InitialMigrationCouponAPI")]
    partial class InitialMigrationCouponAPI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Market.Domain.Models.Coupon", b =>
                {
                    b.Property<long>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CouponId"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("CouponDisccountAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CouponEndDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("CouponMinAmmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CouponStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CouponId");

                    b.ToTable("Coupon", (string)null);

                    b.HasData(
                        new
                        {
                            CouponId = 1L,
                            CouponCode = "50OFF",
                            CouponDisccountAmount = 50.0,
                            CouponEndDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CouponMinAmmount = 1200.0,
                            CouponStartDate = new DateTime(2023, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2023, 12, 29, 20, 37, 16, 679, DateTimeKind.Local).AddTicks(3300),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Special Disccount for New Year",
                            IsDeleted = 0,
                            Name = "50% OFF - New Year Disccount",
                            UpdatedAt = new DateTime(2023, 12, 29, 20, 37, 16, 679, DateTimeKind.Local).AddTicks(3300),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CouponId = 2L,
                            CouponCode = "15OFF",
                            CouponDisccountAmount = 15.0,
                            CouponEndDate = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CouponMinAmmount = 200.0,
                            CouponStartDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2023, 12, 29, 20, 37, 16, 679, DateTimeKind.Local).AddTicks(3349),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Special Disccount for Carnival",
                            IsDeleted = 0,
                            Name = "15% OFF - Carnival Disccount",
                            UpdatedAt = new DateTime(2023, 12, 29, 20, 37, 16, 679, DateTimeKind.Local).AddTicks(3349),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
