// <auto-generated />
using System;
using Market.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Market.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Market.Domain.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Appetizer",
                            CreatedAt = new DateTime(2023, 12, 28, 8, 17, 50, 359, DateTimeKind.Local).AddTicks(8310),
                            CreatedBy = "SYSTEM",
                            Description = " Quisque vel lacus ac magna, vehicula sagittis ut non lacus.<br/> Vestibulum arcu turpis, maximus malesuada neque. Phasellus commodo cursus pretium.",
                            ImageUrl = "https://placehold.co/603x403",
                            IsDeleted = 0,
                            Name = "Pisco Sour",
                            Price = 25.0,
                            UpdatedAt = new DateTime(2023, 12, 28, 8, 17, 50, 359, DateTimeKind.Local).AddTicks(8322),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Appetizer",
                            CreatedAt = new DateTime(2023, 12, 28, 8, 17, 50, 359, DateTimeKind.Local).AddTicks(8349),
                            CreatedBy = "SYSTEM",
                            Description = " Quisque vel lacus ac magna, vehicula sagittis ut non lacus.<br/> Vestibulum arcu turpis, maximus malesuada neque. Phasellus commodo cursus pretium.",
                            ImageUrl = "https://placehold.co/602x402",
                            IsDeleted = 0,
                            Name = "Anticuchos",
                            Price = 20.989999999999998,
                            UpdatedAt = new DateTime(2023, 12, 28, 8, 17, 50, 359, DateTimeKind.Local).AddTicks(8350),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Dessert",
                            CreatedAt = new DateTime(2023, 12, 28, 8, 17, 50, 359, DateTimeKind.Local).AddTicks(8359),
                            CreatedBy = "SYSTEM",
                            Description = " Quisque vel lacus ac magna, vehicula sagittis ut non lacus.<br/> Vestibulum arcu turpis, maximus malesuada neque. Phasellus commodo cursus pretium.",
                            ImageUrl = "https://placehold.co/601x401",
                            IsDeleted = 0,
                            Name = "Suspiro a la Limeña",
                            Price = 12.99,
                            UpdatedAt = new DateTime(2023, 12, 28, 8, 17, 50, 359, DateTimeKind.Local).AddTicks(8359),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Entree",
                            CreatedAt = new DateTime(2023, 12, 28, 8, 17, 50, 359, DateTimeKind.Local).AddTicks(8367),
                            CreatedBy = "SYSTEM",
                            Description = " Quisque vel lacus ac magna, vehicula sagittis ut non lacus.<br/> Vestibulum arcu turpis, maximus malesuada neque. Phasellus commodo cursus pretium.",
                            ImageUrl = "https://placehold.co/600x400",
                            IsDeleted = 0,
                            Name = "Causa al Olivo",
                            Price = 35.0,
                            UpdatedAt = new DateTime(2023, 12, 28, 8, 17, 50, 359, DateTimeKind.Local).AddTicks(8367),
                            UpdatedBy = "SYSTEM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
